alter index color_colection__team_id__idx to color_collection__team_id__idx;
alter index icon_colection__team_id__idx to icon_collection__team_id__idx;
alter index media_bject__file_id__idx rename to media_object__file_id__idx;
